/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import Interfaz.Direc;
import controlescolar.Conexion;
import static controlescolar.Conexion.URL;
import static controlescolar.Conexion.contraseña;
import static controlescolar.Conexion.usuario;
import controlescolar.CorregirRuta;
import controlescolar.FiltroImagenes;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Blob;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

public class CEP extends javax.swing.JFrame {
Conexion conexion = new Conexion();
    PreparedStatement ps;
    ResultSet rs;
    DefaultTableModel modelo;
    public static final String URL ="jdbc:mysql://localhost:3306/controlescolar";
    public static final String usuario="root";
    public static final String contraseña="4321";
    
    public Connection getConnection(){
        Connection con=null;
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
             con=(Connection) DriverManager.getConnection(URL,usuario,contraseña);   
        }catch(Exception ex){
            System.err.println("Error"+ex);
        }
        return con;
    }
    
    public CEP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        PTabbed = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        T_alumnos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbA_grado = new javax.swing.JComboBox<>();
        txtA_w = new javax.swing.JTextField();
        cbA_grupo = new javax.swing.JComboBox<>();
        txtA_telefono = new javax.swing.JTextField();
        cbA_sexo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbA_sangre = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtA_email = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtA_edad = new javax.swing.JTextField();
        A_Consultar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        txtA_estatus = new javax.swing.JTextField();
        cbA_plantel = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtA_nss = new javax.swing.JTextField();
        txtA_am = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtA_nacionalidad = new javax.swing.JTextField();
        txtA_matricula = new javax.swing.JTextField();
        txtA_curp = new javax.swing.JTextField();
        A_buscar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        A_actualizar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        A_eliminar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        A_insertar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtA_nombre = new javax.swing.JTextField();
        txtA_ap = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtA_domicilio = new javax.swing.JTextField();
        foto_txtA = new javax.swing.JTextField();
        txtA_naci = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        fotolabel = new javax.swing.JLabel();
        SeleccAlumn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        T_tutores = new javax.swing.JTable();
        T_consulta = new javax.swing.JButton();
        T_actualizar = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        T_eliminar = new javax.swing.JButton();
        T_insertar = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        txtT_edad = new javax.swing.JTextField();
        txtT_whatsapp = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtT_rfc = new javax.swing.JTextField();
        txtT_nombre = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtT_ap = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtT_am = new javax.swing.JTextField();
        txtT_email = new javax.swing.JTextField();
        T_consultar = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        cbT_sexo = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtT_matricula = new javax.swing.JTextField();
        txtT_nss = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 248, 127));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(255, 255, 255));
        label1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label1.setPreferredSize(new java.awt.Dimension(56, 21));
        label1.setText("Alumnos");
        label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label1MouseClicked(evt);
            }
        });

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setBackground(new java.awt.Color(255, 255, 255));
        label2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label2.setText("Tutor");
        label2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, -1));

        PTabbed.setBackground(new java.awt.Color(255, 255, 194));
        PTabbed.setPreferredSize(new java.awt.Dimension(1324, 600));

        jPanel3.setBackground(new java.awt.Color(255, 255, 194));

        T_alumnos.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        T_alumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Nombre(s)", "Apellido paterno", "Apellido materno", "Sexo ", "Edad", "Domicilio", "Fecha de Nacimiento", "Telefono", "Whatsapp", "Email", "Grupo sanguineo", "NSS", "Estatus", "Nacionalidad", "CURP", "Foto", "Grado", "Grupo"
            }
        ));
        jScrollPane1.setViewportView(T_alumnos);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Whatsapp:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("F. de nacimiento:");

        cbA_grado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbA_grado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        txtA_w.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cbA_grupo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbA_grupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));
        cbA_grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbA_grupoActionPerformed(evt);
            }
        });

        txtA_telefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtA_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtA_telefonoActionPerformed(evt);
            }
        });

        cbA_sexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbA_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        cbA_sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbA_sexoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Telefono:");

        cbA_sangre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbA_sangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+O", "-O", "+A", "-A", "+B", "-B" }));
        cbA_sangre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbA_sangreActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Domicilio:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Edad:");

        txtA_email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtA_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtA_emailActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Estatus:");

        txtA_edad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtA_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtA_edadActionPerformed(evt);
            }
        });

        A_Consultar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        A_Consultar.setText("Consultar");
        A_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_ConsultarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Grupo sanguineo:");

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel50.setText("Plantel:");

        txtA_estatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtA_estatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtA_estatusActionPerformed(evt);
            }
        });

        cbA_plantel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbA_plantel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Ap. Paterno:");

        txtA_nss.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtA_nss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtA_nssActionPerformed(evt);
            }
        });

        txtA_am.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtA_am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtA_amActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("NSS:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Ap. Materno:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Matricula:");

        txtA_nacionalidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtA_nacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtA_nacionalidadActionPerformed(evt);
            }
        });

        txtA_matricula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtA_curp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtA_curp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtA_curpActionPerformed(evt);
            }
        });

        A_buscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        A_buscar.setForeground(new java.awt.Color(0, 0, 153));
        A_buscar.setText("Buscar");
        A_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_buscarActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Grupo:");

        A_actualizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        A_actualizar.setText("Actualizar");
        A_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_actualizarActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("CURP:");

        A_eliminar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        A_eliminar.setForeground(new java.awt.Color(153, 0, 0));
        A_eliminar.setText("Eliminar");
        A_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_eliminarActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Grado:");

        A_insertar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        A_insertar.setForeground(new java.awt.Color(51, 102, 0));
        A_insertar.setText("Insertar");
        A_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_insertarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Sexo:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nombre(s):");

        txtA_nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtA_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtA_nombreActionPerformed(evt);
            }
        });

        txtA_ap.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtA_ap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtA_apActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Nacionalidad:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Foto:");

        txtA_domicilio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtA_domicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtA_domicilioActionPerformed(evt);
            }
        });

        foto_txtA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foto_txtAActionPerformed(evt);
            }
        });

        txtA_naci.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtA_naci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtA_naciActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel1.setText("ALUMNOS PRIMARIA");

        fotolabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        SeleccAlumn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SeleccAlumn.setText("Seleccionar");
        SeleccAlumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccAlumnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(A_insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(A_actualizar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(A_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(567, 567, 567))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtA_am, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel5)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtA_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtA_ap, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtA_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addComponent(jLabel10))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtA_w, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtA_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtA_naci, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtA_domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbA_sexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtA_edad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGap(92, 92, 92)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtA_email, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbA_sangre, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbA_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbA_grado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtA_nss)
                                    .addComponent(txtA_estatus)
                                    .addComponent(txtA_nacionalidad)
                                    .addComponent(txtA_curp, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(A_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel50)
                            .addComponent(jLabel19)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbA_plantel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fotolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(foto_txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(A_Consultar)
                            .addComponent(SeleccAlumn))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbA_plantel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtA_nss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtA_domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtA_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jLabel50))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbA_grado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbA_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtA_estatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(txtA_naci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(txtA_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(foto_txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19)
                                .addComponent(SeleccAlumn)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtA_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtA_curp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(fotolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtA_ap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtA_am, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtA_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtA_w, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(cbA_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtA_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbA_sangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtA_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel12))))))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(A_buscar)
                        .addComponent(A_eliminar)
                        .addComponent(A_Consultar))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(A_insertar)
                        .addComponent(A_actualizar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PTabbed.addTab("Alumnos", jPanel3);

        jPanel5.setBackground(new java.awt.Color(255, 255, 194));

        T_tutores.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        T_tutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Matricula", "Nombre(s)", "Apellido Paterno", "Apellido Materno", "Sexo", "Edad", "Whatsapp", "Email", "NSS", "RFC"
            }
        ));
        jScrollPane2.setViewportView(T_tutores);

        T_consulta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        T_consulta.setForeground(new java.awt.Color(0, 0, 153));
        T_consulta.setText("Buscar");
        T_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_consultaActionPerformed(evt);
            }
        });

        T_actualizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        T_actualizar.setText("Actualizar");
        T_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_actualizarActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("Email:");

        T_eliminar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        T_eliminar.setForeground(new java.awt.Color(153, 0, 0));
        T_eliminar.setText("Eliminar");
        T_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_eliminarActionPerformed(evt);
            }
        });

        T_insertar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        T_insertar.setForeground(new java.awt.Color(51, 102, 0));
        T_insertar.setText("Insertar");
        T_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_insertarActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("Sexo:");

        txtT_edad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtT_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtT_edadActionPerformed(evt);
            }
        });

        txtT_whatsapp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtT_whatsapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtT_whatsappActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel33.setText("RFC:");

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel34.setText("Whatsapp:");

        txtT_rfc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtT_nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtT_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtT_nombreActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel36.setText("Nombre(s):");

        txtT_ap.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtT_ap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtT_apActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel37.setText("Edad:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Ap. Paterno:");

        txtT_am.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtT_am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtT_amActionPerformed(evt);
            }
        });

        txtT_email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtT_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtT_emailActionPerformed(evt);
            }
        });

        T_consultar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        T_consultar.setText("Consultar");
        T_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_consultarActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Ap. Materno:");

        cbT_sexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbT_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        cbT_sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbT_sexoActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("NSS:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Matricula:");

        txtT_matricula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtT_matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtT_matriculaActionPerformed(evt);
            }
        });

        txtT_nss.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel21.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel21.setText("TUTORES PRIMARIA");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtT_matricula)
                                    .addComponent(txtT_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtT_ap, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel28))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbT_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtT_am, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(txtT_whatsapp, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtT_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtT_email, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtT_rfc, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(txtT_nss, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(220, 220, 220)
                .addComponent(jLabel29)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(T_insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(T_actualizar)
                        .addGap(177, 177, 177)
                        .addComponent(T_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157)
                        .addComponent(T_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(T_consultar))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(62, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1032, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(445, 445, 445))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(txtT_nss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtT_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel36)
                                                .addComponent(txtT_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel20)
                                                .addComponent(txtT_ap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel37)
                                                .addComponent(txtT_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel34)
                                                .addComponent(txtT_whatsapp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(7, 7, 7)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel33)
                                                .addComponent(txtT_rfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtT_am, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel22))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(cbT_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel28)))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel27)
                                                .addComponent(txtT_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel23))))))
                        .addGap(70, 70, 70)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T_actualizar)
                    .addComponent(T_consulta)
                    .addComponent(T_insertar)
                    .addComponent(T_consultar)
                    .addComponent(T_eliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PTabbed.addTab("Tutores", jPanel4);

        getContentPane().add(PTabbed, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, -31, 1141, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbA_grupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbA_grupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbA_grupoActionPerformed

    private void txtA_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtA_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtA_telefonoActionPerformed

    private void cbA_sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbA_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbA_sexoActionPerformed

    private void cbA_sangreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbA_sangreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbA_sangreActionPerformed

    private void txtA_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtA_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtA_emailActionPerformed

    private void txtA_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtA_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtA_edadActionPerformed

    private void A_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_ConsultarActionPerformed
        Connection con = null;
        con=getConnection();
        DefaultTableModel tconsulta = new DefaultTableModel();
        tconsulta.addColumn("Matricula");
        tconsulta.addColumn("Nombre_A");
        tconsulta.addColumn("AP_A");
        tconsulta.addColumn("AM_A");
        tconsulta.addColumn("Sexo_A");
        tconsulta.addColumn("Edad_A");
        tconsulta.addColumn("Domicilio_A");
        tconsulta.addColumn("FechaN_A");
        tconsulta.addColumn("Telefono_T");
        tconsulta.addColumn("Whatsapp_A");
        tconsulta.addColumn("Email_A");
        tconsulta.addColumn("GSanguineo_A");
        tconsulta.addColumn("NSS_A");
        tconsulta.addColumn("Estatus_A");
        tconsulta.addColumn("Nacionalidad_A");
        tconsulta.addColumn("CURP_A");
        tconsulta.addColumn("Grado");
        tconsulta.addColumn("Grupo");
        tconsulta.addColumn("ID_Plantel");
        T_alumnos.setModel(tconsulta);

        String []datos = new String[19];
        try{
            Statement leer = con.createStatement();
            rs = leer.executeQuery("SELECT Matricula, Nombre_A, AP_A, AM_A, Sexo_A, Edad_A, Domicilio_A, FechaN_A,"
                    + "Telefono_T, Whatsapp_A, Email_A, GSanguineo_A, NSS_A, Estatus_A, Nacionalidad_A,"
                    + "CURP_A, Grado, Grupo, ID_Plantel FROM tbl_alumno WHERE ID_PLANTEL=1");
            while(rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);
                datos[7] = rs.getString(8);
                datos[8] = rs.getString(9);
                datos[9] = rs.getString(10);
                datos[10] = rs.getString(11);
                datos[11] = rs.getString(12);
                datos[12] = rs.getString(13);
                datos[13] = rs.getString(14);
                datos[14] = rs.getString(15);
                datos[15] = rs.getString(16);
                datos[16] = rs.getString(17);
                datos[17] = rs.getString(18);
                datos[18] = rs.getString(19);
                tconsulta.addRow(datos);
            }
            T_alumnos.setModel(tconsulta);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e + "Error en la consulta");
        }
    }//GEN-LAST:event_A_ConsultarActionPerformed

    private void txtA_estatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtA_estatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtA_estatusActionPerformed

    private void txtA_nssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtA_nssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtA_nssActionPerformed

    private void txtA_amActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtA_amActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtA_amActionPerformed

    private void txtA_nacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtA_nacionalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtA_nacionalidadActionPerformed

    private void txtA_curpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtA_curpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtA_curpActionPerformed

    private void A_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_buscarActionPerformed
       Connection con = null;
        try{
            con=getConnection();
            PreparedStatement ps = con.prepareStatement("SELECT * FROM tbl_alumno WHERE Matricula = ?");
            ps.setString(1, txtA_matricula.getText());
            rs = ps.executeQuery();
            File file=new File("Ruta_Foto");

            if(rs.next()){
                txtA_matricula.setText(rs.getString("Matricula"));
                txtA_nombre.setText(rs.getString("Nombre_A"));
                txtA_ap.setText(rs.getString("AP_A"));
                txtA_am.setText(rs.getString("AM_A"));
                cbA_sexo.setSelectedItem(rs.getString("Sexo_A"));
                txtA_edad.setText(rs.getString("Edad_A"));
                txtA_domicilio.setText(rs.getString("Domicilio_A"));
                txtA_naci.setText(rs.getString("FechaN_A"));
                txtA_telefono.setText(rs.getString("Telefono_T"));
                txtA_w.setText(rs.getString("Whatsapp_A"));
                txtA_email.setText(rs.getString("Email_A"));
                cbA_sangre.setSelectedItem(rs.getString("GSanguineo_A"));
                txtA_nss.setText(rs.getString("NSS_A"));
                txtA_estatus.setText(rs.getString("Estatus_A"));
                txtA_nacionalidad.setText(rs.getString("Nacionalidad_A"));
                txtA_curp.setText(rs.getString("CURP_A"));
                foto_txtA.setText(rs.getString("Ruta_Foto"));
                cbA_grado.setSelectedItem(rs.getString("Grado"));
                cbA_grupo.setSelectedItem(rs.getString("Grupo"));
                cbA_plantel.setSelectedItem(rs.getString("ID_Plantel"));
                Image foto = getToolkit().getImage(rs.getString("Ruta_Foto"));
                foto = foto.getScaledInstance(110, 110, Image.SCALE_DEFAULT);
                fotolabel.setIcon(new ImageIcon(foto));

            }
            else{
                JOptionPane.showMessageDialog(null, "No existe un alumno con esa Matricula");
            }
        }
        catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_A_buscarActionPerformed

    private void A_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_actualizarActionPerformed
       Connection con = null;

       try{
            con = getConnection();
           FileInputStream archivofoto;
           String id = txtA_matricula.getText();
           String nombre = txtA_nombre.getText();
           String ap = txtA_ap.getText();
           String am = txtA_am.getText();
           String sexo = cbA_sexo.getSelectedItem().toString();           
           int edad = Integer.parseInt(txtA_edad.getText());
           String domicilio = txtA_domicilio.getText();
           Date fechaN = Date.valueOf(txtA_naci.getText());
           String telefono = txtA_telefono.getText();
           String whatsapp = txtA_w.getText();
           String email = txtA_email.getText();
           String sangre = cbA_sangre.getSelectedItem().toString();
           String nss = txtA_nss.getText();
           String estatus = txtA_estatus.getText();
           String nacionalidad = txtA_nacionalidad.getText();
           String curp = txtA_curp.getText();
           int grado = Integer.parseInt(cbA_grado.getSelectedItem().toString());
           String grupo = cbA_grupo.getSelectedItem().toString();
           String plantel = cbA_plantel.getSelectedItem().toString();
           archivofoto = new FileInputStream(foto_txtA.getText());
           String foto = foto_txtA.getText();
          String strRutaImagen;
            CorregirRuta ruta1 = new CorregirRuta(foto_txtA.getText(),"\\\\", "\\\\\\\\");
            strRutaImagen = ruta1.obtenerRutaCorregidaWindows();
                     
           
            String query = "UPDATE tbl_alumno SET Nombre_A='"+nombre+"', AP_A= '"+ap+"', AM_A= '"+am
            +"', Sexo_A= '"+sexo+"', Edad_A= '"+edad+"', Domicilio_A='"+domicilio+"', FechaN_A='"+fechaN+"', Telefono_T='"+telefono
            +"', Whatsapp_A= '"+whatsapp+"', Email_A='"+email+"', GSanguineo_A= '"+sangre
            +"', NSS_A= '"+nss+"', Estatus_A='"+estatus+"', Nacionalidad_A='"+nacionalidad
            +"', CURP_A='"+curp+"', Foto_A= '"+archivofoto+"', Grado='"+grado+"', Grupo='"+grupo+"', ID_Plantel= '"+plantel+"', Ruta_Foto='"+strRutaImagen+"'  "
            + "WHERE Matricula= '"+id+"'";
                   

          Statement stmt = con.createStatement();
          stmt.executeUpdate(query);   
          JOptionPane.showMessageDialog(null, "Alumno actualizado");
          limpiarCaja();

        }
        catch(Exception ex){
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, ex + "Error al actualizar alumno");
        }
    }//GEN-LAST:event_A_actualizarActionPerformed

    private void A_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_eliminarActionPerformed
        Connection con = null;
        try{
            con = getConnection();

            String matricula_a = txtA_matricula.getText();

            String query = "DELETE FROM tbl_alumno WHERE Matricula='"+matricula_a+"'" ;

            Statement stmt = con.createStatement();
            stmt.executeUpdate(query);
            
            JOptionPane.showMessageDialog(null, "Alumno eliminado");
            limpiarCaja();

        }
        catch(Exception ex){
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, ex + "Error al eliminar alumno");
        }
    }//GEN-LAST:event_A_eliminarActionPerformed

    private void A_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_insertarActionPerformed
       Connection con = null;

       try{
            con = getConnection();
            FileInputStream archivofoto;
           String matricula = txtA_matricula.getText();
           String nombre = txtA_nombre.getText();
           String ap = txtA_ap.getText();
           String am = txtA_am.getText();
           String sexo = cbA_sexo.getSelectedItem().toString();           
           int edad = Integer.parseInt(txtA_edad.getText());
           String domicilio = txtA_domicilio.getText();
           Date fechaN = Date.valueOf(txtA_naci.getText());
           String telefono = txtA_telefono.getText();
           String whatsapp = txtA_w.getText();
           String email = txtA_email.getText();
           String sangre = cbA_sangre.getSelectedItem().toString();
           String nss = txtA_nss.getText();
           String estatus = txtA_estatus.getText();
           String nacionalidad = txtA_nacionalidad.getText();
           String curp = txtA_curp.getText();
           int grado = Integer.parseInt(cbA_grado.getSelectedItem().toString());
           String grupo = cbA_grupo.getSelectedItem().toString();
           String plantel = cbA_plantel.getSelectedItem().toString();
           archivofoto = new FileInputStream(foto_txtA.getText());
           String foto = foto_txtA.getText();
           String strRutaImagen;
        CorregirRuta ruta1 = new CorregirRuta(foto_txtA.getText(),"\\", "\\\\");
        strRutaImagen = ruta1.obtenerRutaCorregidaWindows();
           
            String query = "INSERT INTO tbl_alumno"
            + "(Matricula, Nombre_A, AP_A, AM_A, Sexo_A, Edad_A, Domicilio_A, FechaN_A, Telefono_T, Whatsapp_A, Email_A, "
            + "GSanguineo_A, NSS_A, Estatus_A, Nacionalidad_A, CURP_A, Foto_A, Grado, Grupo, ID_Plantel, Ruta_Foto)"
            + "VALUES('"+matricula+"', '"+nombre+"', '"+ap+"', '"+am+"', '"+sexo+"', '"+edad+"', '"+domicilio
            +"', '"+fechaN+"', '"+telefono+"', '"+whatsapp+"', '"+email+"', '"+sangre+"', '"+nss+"', '"+estatus
            +"', '"+nacionalidad+"', '"+curp+"', '"+archivofoto+"', '"+grado+"', '"+grupo+"', '"+plantel+"', '"+strRutaImagen+"')";
           
          Statement stmt = con.createStatement();
          stmt.executeUpdate(query);   
          JOptionPane.showMessageDialog(null, "Alumno agregado");
          limpiarCaja();

        }
        catch(Exception ex){
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, ex + "Error al agregar alumno");
        }
    }//GEN-LAST:event_A_insertarActionPerformed

    private void txtA_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtA_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtA_nombreActionPerformed

    private void txtA_apActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtA_apActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtA_apActionPerformed

    private void txtA_domicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtA_domicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtA_domicilioActionPerformed

    private void foto_txtAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foto_txtAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foto_txtAActionPerformed

    private void txtA_naciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtA_naciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtA_naciActionPerformed

    private void T_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_consultaActionPerformed
        Connection con = null;
        try{
            con=getConnection();
            PreparedStatement ps = con.prepareStatement("SELECT * FROM tbl_tutor WHERE Matricula = ?");
            ps.setString(1, txtT_matricula.getText());
            rs = ps.executeQuery();
            if(rs.next()){
                txtT_nombre.setText(rs.getString("Nombre_T"));
                txtT_ap.setText(rs.getString("AP_T"));
                txtT_am.setText(rs.getString("AM_T"));
                cbT_sexo.setSelectedItem(rs.getString("Sexo_T"));
                txtT_edad.setText(rs.getString("Edad_T"));
                txtT_whatsapp.setText(rs.getString("Whatsapp_T"));
                txtT_email.setText(rs.getString("Email_T"));
                txtT_nss.setText(rs.getString("NSS_T"));
                txtT_rfc.setText(rs.getString("Estatus_T"));
                txtT_matricula.setText(rs.getString("Matricula"));

            }
            else{
                JOptionPane.showMessageDialog(null, "No existe tutor de esa Matricula");
            }
        }
        catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_T_consultaActionPerformed

    private void T_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_actualizarActionPerformed
        Connection con = null;

        try{
            con = getConnection();
            String matricula = txtT_matricula.getText();
            String nombre = txtT_nombre.getText();
            String ap = txtT_ap.getText();
            String am = txtT_am.getText();
            String sexo = cbT_sexo.getSelectedItem().toString();
            int edad = Integer.parseInt(txtT_edad.getText());
            String whatsapp = txtT_whatsapp.getText();
            String email = txtT_email.getText();
            String nss = txtT_nss.getText();
            String rfc = txtT_rfc.getText();

            String query = "UPDATE tbl_tutor SET Nombre_T='"+nombre+"', AP_T= '"+ap+"', AM_T= '"+am
            +"', Sexo_T= '"+sexo+"', Edad_T= '"+edad+"', Whatsapp_A= '"+whatsapp+"', Email_A='"+email+"', NSS_A= '"+nss+"', RFC_T='"+rfc+"' "
            + "WHERE Matricula= '"+matricula+"'";

            Statement stmt = con.createStatement();
            stmt.executeUpdate(query);
            
            JOptionPane.showMessageDialog(null, "Datos del tutor actualizado");
            limpiarCaja();

        }
        catch(Exception ex){
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, ex + "Error al actualizar tutor");
        }
    }//GEN-LAST:event_T_actualizarActionPerformed

    private void T_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_eliminarActionPerformed
        Connection con = null;
        try{
            con = getConnection();
            String matricula = txtT_matricula.getText();

            String query = "DELETE FROM tbl_tutor WHERE Matricula='"+matricula+"'";

            Statement stmt = con.createStatement();
            stmt.executeUpdate(query);
            
            JOptionPane.showMessageDialog(null, "Tutor eliminado");
            limpiarCaja();

        }
        catch(Exception ex){
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, ex + "Error al eliminar tutor");
        }
    }//GEN-LAST:event_T_eliminarActionPerformed

    private void T_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_insertarActionPerformed
        Connection con = null;

        try{
            con = getConnection();
            String matricula = txtT_matricula.getText();
            String nombre = txtT_nombre.getText();
            String ap = txtT_ap.getText();
            String am = txtT_am.getText();
            String sexo = cbT_sexo.getSelectedItem().toString();
            int edad = Integer.parseInt(txtT_edad.getText());
            String whatsapp = txtT_whatsapp.getText();
            String email = txtT_email.getText();
            String nss = txtT_nss.getText();
            String rfc = txtT_rfc.getText();

            String query = "INSERT INTO tbl_tutor"
            + "(Nombre_T, AP_T, AM_T, Sexo_T,  Whatsapp_T, Email_T, NSS_T, RFC_T)"
            + "VALUES('"+nombre+"', '"+ap+"', '"+am+"', '"+sexo+"', '"+edad+"', '"+whatsapp+"', '"+email+"', '"+nss+"', '"+rfc+"', '"+matricula+"')";

            Statement stmt = con.createStatement();
            stmt.executeUpdate(query);
            
            JOptionPane.showMessageDialog(null, "Nuevo tutor agregado");
            limpiarCaja();

        }
        catch(Exception ex){
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, ex + "Error al agregar tutor");
        }
    }//GEN-LAST:event_T_insertarActionPerformed

    private void txtT_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtT_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtT_edadActionPerformed

    private void txtT_whatsappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtT_whatsappActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtT_whatsappActionPerformed

    private void txtT_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtT_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtT_nombreActionPerformed

    private void txtT_apActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtT_apActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtT_apActionPerformed

    private void txtT_amActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtT_amActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtT_amActionPerformed

    private void txtT_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtT_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtT_emailActionPerformed

    private void T_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_consultarActionPerformed
        Connection con = null;
        con=getConnection();
        DefaultTableModel tconsulta = new DefaultTableModel();
        tconsulta.addColumn("Nombre_T");
        tconsulta.addColumn("AP_T");
        tconsulta.addColumn("AM_T");
        tconsulta.addColumn("Sexo_T");
        tconsulta.addColumn("Edad_T");
        tconsulta.addColumn("Whatsapp_T");
        tconsulta.addColumn("Email_T");
        tconsulta.addColumn("NSS_T");
        tconsulta.addColumn("RFC_T");
        tconsulta.addColumn("Matricula");
        T_tutores.setModel(tconsulta);

        String []datos = new String[10];
        try{
            Statement leer = con.createStatement();
            rs = leer.executeQuery("SELECT * FROM tbl_tutor");
            while(rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);
                datos[7] = rs.getString(8);
                datos[8] = rs.getString(9);
                datos[9] = rs.getString(10);

                tconsulta.addRow(datos);
            }
            T_tutores.setModel(tconsulta);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e + "Error en la consulta");
        }
    }//GEN-LAST:event_T_consultarActionPerformed

    private void cbT_sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbT_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbT_sexoActionPerformed

    private void txtT_matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtT_matriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtT_matriculaActionPerformed

    private void label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label1MouseClicked
        // TODO add your handling code here:
        PTabbed.setSelectedIndex(0);
    }//GEN-LAST:event_label1MouseClicked

    private void label2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label2MouseClicked
        // TODO add your handling code here:
        PTabbed.setSelectedIndex(1);
    }//GEN-LAST:event_label2MouseClicked

    private void SeleccAlumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccAlumnActionPerformed
       String strSeleccionado;
       JFileChooser jfcSeleccionarArchivo = new JFileChooser();
       jfcSeleccionarArchivo.addChoosableFileFilter(new FiltroImagenes());
       jfcSeleccionarArchivo.setFileFilter(jfcSeleccionarArchivo.getChoosableFileFilters()[1]);
       int retval = jfcSeleccionarArchivo.showOpenDialog(null);
          if (retval == JFileChooser.APPROVE_OPTION)
          {
              //... Si el usuario selecciono un archivo, entonces usarlo
              File filSeleccionado = jfcSeleccionarArchivo.getSelectedFile();
              //Obtener ruta absoluta del archivo seleccionado
              strSeleccionado = filSeleccionado.getAbsolutePath();
              //Mostrar la ruta al usuario en el area de texto correspondiente
              foto_txtA.setText(strSeleccionado);
              
          }
       
        Image foto = getToolkit().getImage(foto_txtA.getText());
        foto = foto.getScaledInstance(110, 110, Image.SCALE_DEFAULT);
        fotolabel.setIcon(new ImageIcon(foto));
    }//GEN-LAST:event_SeleccAlumnActionPerformed
 private void limpiarCaja(){
            txtA_matricula.setText(null);
            txtA_nombre.setText(null);
            txtA_ap.setText(null);
            txtA_am.setText(null);
            cbA_sexo.setSelectedIndex(0);
            txtA_edad.setText(null);
            txtA_domicilio.setText(null);
            txtA_naci.setText(null);
            txtA_telefono.setText(null);
            txtA_w.setText(null);
            txtA_email.setText(null);
            cbA_sangre.setSelectedIndex(0);
            txtA_nss.setText(null);
            txtA_estatus.setText(null);
            txtA_nacionalidad.setText(null);
            txtA_curp.setText(null);
            foto_txtA.setText(null);
            cbA_grado.setSelectedIndex(0);
            cbA_grupo.setSelectedIndex(0);
            cbA_plantel.setSelectedIndex(0);
            txtT_nombre.setText(null);
            txtT_ap.setText(null);
            txtT_am.setText(null);
            cbT_sexo.setSelectedIndex(0);
            txtT_edad.setText(null);
            txtT_whatsapp.setText(null);
           txtT_email.setText(null);
           txtT_nss.setText(null);
           txtT_rfc.setText(null);
           txtT_matricula.setText(null);
           fotolabel.setIcon(null);
            }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CEP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CEP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CEP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CEP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CEP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A_Consultar;
    private javax.swing.JButton A_actualizar;
    private javax.swing.JButton A_buscar;
    private javax.swing.JButton A_eliminar;
    private javax.swing.JButton A_insertar;
    private javax.swing.JTabbedPane PTabbed;
    private javax.swing.JButton SeleccAlumn;
    private javax.swing.JButton T_actualizar;
    private javax.swing.JTable T_alumnos;
    private javax.swing.JButton T_consulta;
    private javax.swing.JButton T_consultar;
    private javax.swing.JButton T_eliminar;
    private javax.swing.JButton T_insertar;
    private javax.swing.JTable T_tutores;
    private javax.swing.JComboBox<String> cbA_grado;
    private javax.swing.JComboBox<String> cbA_grupo;
    private javax.swing.JComboBox<String> cbA_plantel;
    private javax.swing.JComboBox<String> cbA_sangre;
    private javax.swing.JComboBox<String> cbA_sexo;
    private javax.swing.JComboBox<String> cbT_sexo;
    private javax.swing.JTextField foto_txtA;
    private javax.swing.JLabel fotolabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JTextField txtA_am;
    private javax.swing.JTextField txtA_ap;
    private javax.swing.JTextField txtA_curp;
    private javax.swing.JTextField txtA_domicilio;
    private javax.swing.JTextField txtA_edad;
    private javax.swing.JTextField txtA_email;
    private javax.swing.JTextField txtA_estatus;
    private javax.swing.JTextField txtA_matricula;
    private javax.swing.JTextField txtA_naci;
    private javax.swing.JTextField txtA_nacionalidad;
    private javax.swing.JTextField txtA_nombre;
    private javax.swing.JTextField txtA_nss;
    private javax.swing.JTextField txtA_telefono;
    private javax.swing.JTextField txtA_w;
    private javax.swing.JTextField txtT_am;
    private javax.swing.JTextField txtT_ap;
    private javax.swing.JTextField txtT_edad;
    private javax.swing.JTextField txtT_email;
    private javax.swing.JTextField txtT_matricula;
    private javax.swing.JTextField txtT_nombre;
    private javax.swing.JTextField txtT_nss;
    private javax.swing.JTextField txtT_rfc;
    private javax.swing.JTextField txtT_whatsapp;
    // End of variables declaration//GEN-END:variables
}
