/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import controlescolar.Conexion;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Direc extends javax.swing.JFrame {
    Conexion conexion = new Conexion();
    PreparedStatement ps;
    ResultSet rs;
    DefaultTableModel modelo;
    public static final String URL ="jdbc:mysql://localhost:3306/controlescolar";
    public static final String usuario="root";
    public static final String contraseña="l0v3s70r717309";
    
    public Connection getConnection(){
        Connection con=null;
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
             con=(Connection) DriverManager.getConnection(URL,usuario,contraseña); 
        }catch(Exception ex){
            System.err.println("Error"+ex);
        }
        return con;
    }
    
    public Direc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        DTabbed = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        A_consultar = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        T_alumnos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        T_consultar = new javax.swing.JButton();
        jLabel116 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        T_tutores = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel129 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        T_pago = new javax.swing.JTable();
        P_consultar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        C_consultar = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        T_colegiatura = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        T_plantel = new javax.swing.JTable();
        PL_consultar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        T_corte = new javax.swing.JTable();
        CR_consultar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaRI = new javax.swing.JTable();
        MatriculaRI = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ConGI = new java.awt.Label();
        ConDI = new java.awt.Label();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        ConsultaDetalladaTodo = new java.awt.Label();
        GradoRGGG = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ReporteGralTabla = new javax.swing.JTable();
        ConsultaGralGrado = new java.awt.Label();
        jLabel11 = new javax.swing.JLabel();
        GrupoReporteGral = new javax.swing.JComboBox<>();
        ConsultaGralGrupo = new java.awt.Label();
        jLabel12 = new javax.swing.JLabel();
        ConsultaDetalladaPlantel = new java.awt.Label();
        jLabel14 = new javax.swing.JLabel();
        PlantelReporteGral = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        ConsultaDetalladaGrado1 = new java.awt.Label();
        ConsultaGralPlantel = new java.awt.Label();
        jLabel16 = new javax.swing.JLabel();
        ConsultaDetalladaGrupo1 = new java.awt.Label();
        ConsultaGralTodo = new java.awt.Label();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 248, 127));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(255, 255, 255));
        label1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label1.setText("Pago");
        label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label1MouseClicked(evt);
            }
        });

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setBackground(new java.awt.Color(255, 255, 255));
        label2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label2.setText("Alumnos");
        label2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label2MouseClicked(evt);
            }
        });

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(new java.awt.Color(255, 255, 255));
        label3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label3.setText("Tutores");
        label3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label3MouseClicked(evt);
            }
        });

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setBackground(new java.awt.Color(255, 255, 255));
        label4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label4.setText("Colegiatura");
        label4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label4MouseClicked(evt);
            }
        });

        label5.setAlignment(java.awt.Label.CENTER);
        label5.setBackground(new java.awt.Color(255, 255, 255));
        label5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label5.setText("Reporte individual");
        label5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label5MouseClicked(evt);
            }
        });

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setBackground(new java.awt.Color(255, 255, 255));
        label6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label6.setText("Reporte general");
        label6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label6MouseClicked(evt);
            }
        });

        label7.setAlignment(java.awt.Label.CENTER);
        label7.setBackground(new java.awt.Color(255, 255, 255));
        label7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label7.setText("Plantel");
        label7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label7MouseClicked(evt);
            }
        });

        label8.setAlignment(java.awt.Label.CENTER);
        label8.setBackground(new java.awt.Color(255, 255, 255));
        label8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label8.setText("Corte");
        label8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 570));

        DTabbed.setBackground(new java.awt.Color(255, 255, 194));
        DTabbed.setPreferredSize(new java.awt.Dimension(1074, 500));

        jPanel8.setBackground(new java.awt.Color(255, 255, 194));

        A_consultar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        A_consultar.setText("Consultar");
        A_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_consultarActionPerformed(evt);
            }
        });

        T_alumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Nombre(s)", "Apellido paterno", "Apellido materno", "Sexo ", "Domicilio", "Fecha de Nacimiento", "Telefono", "Whatsapp", "Email", "Grupo sanguineo", "NSS", "Estatus", "Nacionalidad", "CURP", "Foto", "Grado", "Grupo"
            }
        ));
        jScrollPane6.setViewportView(T_alumnos);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel1.setText("ALUMNOS");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(465, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(A_consultar))
                .addGap(435, 435, 435))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(A_consultar)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        DTabbed.addTab("Alumnos", jPanel8);

        jPanel10.setBackground(new java.awt.Color(255, 255, 194));

        T_consultar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        T_consultar.setText("Consultar");
        T_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_consultarActionPerformed(evt);
            }
        });

        T_tutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Matricula", "Nombre(s)", "Apellido Paterno", "Apellido Materno", "Sexo", "Edad", "Whatsapp", "Email", "NSS", "RFC"
            }
        ));
        jScrollPane7.setViewportView(T_tutores);

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel2.setText("TUTORES");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 1032, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel116))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(488, 488, 488)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(T_consultar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(53, 53, 53)
                .addComponent(T_consultar)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel116))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        DTabbed.addTab("Tutores", jPanel9);

        jPanel11.setBackground(new java.awt.Color(255, 255, 194));

        T_pago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Pago", "Cantidad", "Monto", "Fecha de pago", "Mes", "Matricula del alumno", "Grado ", "Grupo"
            }
        ));
        jScrollPane8.setViewportView(T_pago);

        P_consultar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        P_consultar.setText("Consultar");
        P_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_consultarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel3.setText("PAGO");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel129)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(469, 469, 469))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(P_consultar)
                        .addGap(453, 453, 453))))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 927, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(39, 39, 39)
                .addComponent(P_consultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel129)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        DTabbed.addTab("Pago", jPanel11);

        jPanel12.setBackground(new java.awt.Color(255, 255, 194));

        C_consultar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        C_consultar.setText("Consultar");
        C_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_consultarActionPerformed(evt);
            }
        });

        T_colegiatura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Colegiatura", "Cantidad", "Fecha de corte", "Matricula del alimno", "Numero de Pago", "Numero de corte"
            }
        ));
        jScrollPane9.setViewportView(T_colegiatura);

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel4.setText("COLEGIATURA");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(428, 428, 428)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 927, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(C_consultar)
                        .addGap(455, 455, 455))))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addGap(43, 43, 43)
                .addComponent(C_consultar)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        DTabbed.addTab("Colegiatura", jPanel12);

        jPanel2.setBackground(new java.awt.Color(255, 255, 194));
        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 800));
        jPanel2.setPreferredSize(new java.awt.Dimension(995, 500));

        T_plantel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID_Plantel", "Tipo_Plantel"
            }
        ));
        jScrollPane10.setViewportView(T_plantel);

        PL_consultar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PL_consultar.setText("Consultar");
        PL_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PL_consultarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel5.setText("PLANTEL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 459, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PL_consultar)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(442, 442, 442))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGap(62, 62, 62)
                .addComponent(PL_consultar)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        DTabbed.addTab("Plantel", jPanel2);

        jPanel13.setBackground(new java.awt.Color(255, 255, 194));

        T_corte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID_Corte", "Fecha_Inicio", "Fecha Fin"
            }
        ));
        jScrollPane11.setViewportView(T_corte);

        CR_consultar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CR_consultar.setText("Consultar");
        CR_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CR_consultarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel6.setText("CORTE");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(0, 139, Short.MAX_VALUE)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CR_consultar)
                    .addComponent(jLabel6))
                .addGap(445, 445, 445))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addGap(39, 39, 39)
                .addComponent(CR_consultar)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        DTabbed.addTab("Corte", jPanel13);

        jPanel5.setBackground(new java.awt.Color(255, 255, 194));

        TablaRI.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        TablaRI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(TablaRI);

        MatriculaRI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Matricula:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("¿Qué desea conocer?");

        ConGI.setAlignment(java.awt.Label.CENTER);
        ConGI.setBackground(new java.awt.Color(255, 255, 255));
        ConGI.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ConGI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ConGI.setText("Consulta general");
        ConGI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConGIMouseClicked(evt);
            }
        });

        ConDI.setAlignment(java.awt.Label.CENTER);
        ConDI.setBackground(new java.awt.Color(255, 255, 255));
        ConDI.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ConDI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ConDI.setText("Consulta detallada");
        ConDI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConDIMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel13.setText("REPORTE INDIVIDUAL");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(MatriculaRI, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154)
                        .addComponent(ConGI, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(ConDI, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(jLabel13)))
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(245, 245, 245))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel13)
                .addGap(48, 48, 48)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConDI, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConGI, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7)
                        .addComponent(MatriculaRI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        DTabbed.addTab("Reporte Indv", jPanel5);

        jPanel3.setBackground(new java.awt.Color(255, 255, 194));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Consulta por GRUPO");

        ConsultaDetalladaTodo.setAlignment(java.awt.Label.CENTER);
        ConsultaDetalladaTodo.setBackground(new java.awt.Color(255, 255, 255));
        ConsultaDetalladaTodo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ConsultaDetalladaTodo.setText("Consulta detallada");
        ConsultaDetalladaTodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultaDetalladaTodoMouseClicked(evt);
            }
        });

        GradoRGGG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        GradoRGGG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Grado:");

        ReporteGralTabla.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ReporteGralTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(ReporteGralTabla);

        ConsultaGralGrado.setAlignment(java.awt.Label.CENTER);
        ConsultaGralGrado.setBackground(new java.awt.Color(255, 255, 255));
        ConsultaGralGrado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ConsultaGralGrado.setText("Consulta detallada");
        ConsultaGralGrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultaGralGradoMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Grupo:");

        GrupoReporteGral.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        GrupoReporteGral.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B" }));

        ConsultaGralGrupo.setAlignment(java.awt.Label.CENTER);
        ConsultaGralGrupo.setBackground(new java.awt.Color(255, 255, 255));
        ConsultaGralGrupo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ConsultaGralGrupo.setText("Consulta general");
        ConsultaGralGrupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultaGralGrupoMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Consulta por GRADO");

        ConsultaDetalladaPlantel.setAlignment(java.awt.Label.CENTER);
        ConsultaDetalladaPlantel.setBackground(new java.awt.Color(255, 255, 255));
        ConsultaDetalladaPlantel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ConsultaDetalladaPlantel.setText("Consulta general");
        ConsultaDetalladaPlantel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultaDetalladaPlantelMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Plantel:");

        PlantelReporteGral.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PlantelReporteGral.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KINDER", "PRIMARIA", "SECUNDARIA" }));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Consulta por PLANTEL");

        ConsultaDetalladaGrado1.setAlignment(java.awt.Label.CENTER);
        ConsultaDetalladaGrado1.setBackground(new java.awt.Color(255, 255, 255));
        ConsultaDetalladaGrado1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ConsultaDetalladaGrado1.setText("Consulta general");
        ConsultaDetalladaGrado1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultaDetalladaGrado1MouseClicked(evt);
            }
        });

        ConsultaGralPlantel.setAlignment(java.awt.Label.CENTER);
        ConsultaGralPlantel.setBackground(new java.awt.Color(255, 255, 255));
        ConsultaGralPlantel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ConsultaGralPlantel.setText("Consulta detallada");
        ConsultaGralPlantel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultaGralPlantelMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Consulta TOTAL");

        ConsultaDetalladaGrupo1.setAlignment(java.awt.Label.CENTER);
        ConsultaDetalladaGrupo1.setBackground(new java.awt.Color(255, 255, 255));
        ConsultaDetalladaGrupo1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ConsultaDetalladaGrupo1.setText("Consulta detallada");
        ConsultaDetalladaGrupo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultaDetalladaGrupo1MouseClicked(evt);
            }
        });

        ConsultaGralTodo.setAlignment(java.awt.Label.CENTER);
        ConsultaGralTodo.setBackground(new java.awt.Color(255, 255, 255));
        ConsultaGralTodo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ConsultaGralTodo.setText("Consulta general");
        ConsultaGralTodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultaGralTodoMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel17.setText("REPORTE GENERAL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GrupoReporteGral, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GradoRGGG, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PlantelReporteGral, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(143, 143, 143)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(ConsultaGralGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ConsultaDetalladaGrupo1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                        .addGap(100, 100, 100)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(ConsultaGralGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConsultaDetalladaGrado1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConsultaDetalladaPlantel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConsultaGralPlantel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(jLabel16)
                        .addGap(56, 56, 56)
                        .addComponent(ConsultaDetalladaTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(ConsultaGralTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(jLabel17)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GrupoReporteGral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GradoRGGG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ConsultaDetalladaGrupo1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConsultaGralGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConsultaGralPlantel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConsultaGralGrupo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConsultaDetalladaGrado1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConsultaDetalladaPlantel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlantelReporteGral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel16))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConsultaGralTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConsultaDetalladaTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );

        DTabbed.addTab("ReporteGralGrado", jPanel3);

        getContentPane().add(DTabbed, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, -32, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_consultarActionPerformed
       Connection con = null;
        con=getConnection();
        DefaultTableModel tconsulta = new DefaultTableModel();
        tconsulta.addColumn("Matricula");
        tconsulta.addColumn("Nombre_A");
        tconsulta.addColumn("AP_A");
        tconsulta.addColumn("AM_A");
        tconsulta.addColumn("Sexo_A");
        tconsulta.addColumn("Edad_A");
        tconsulta.addColumn("Domicilio_A");
        tconsulta.addColumn("FechaN_A");
        tconsulta.addColumn("Telefono_T");
        tconsulta.addColumn("Whatsapp_A");
        tconsulta.addColumn("Email_A");
        tconsulta.addColumn("GSanguineo_A");
        tconsulta.addColumn("NSS_A");
        tconsulta.addColumn("Estatus_A");
        tconsulta.addColumn("Nacionalidad_A");
        tconsulta.addColumn("CURP_A");
        tconsulta.addColumn("Grado");
        tconsulta.addColumn("Grupo");
        tconsulta.addColumn("ID_Plantel");
        T_alumnos.setModel(tconsulta);

                String []datos = new String[19];
        try{
            Statement leer = con.createStatement();
            rs = leer.executeQuery("SELECT Matricula, Nombre_A, AP_A, AM_A, Sexo_A, Edad_A, Domicilio_A, FechaN_A,"
                    + "Telefono_T, Whatsapp_A, Email_A, GSanguineo_A, NSS_A, Estatus_A, Nacionalidad_A,"
                    + "CURP_A, Grado, Grupo, ID_Plantel FROM tbl_alumno");
        while(rs.next()){
        datos[0] = rs.getString(1);
        datos[1] = rs.getString(2);
        datos[2] = rs.getString(3);
        datos[3] = rs.getString(4);
        datos[4] = rs.getString(5);
        datos[5] = rs.getString(6);
        datos[6] = rs.getString(7);
        datos[7] = rs.getString(8);
        datos[8] = rs.getString(9);
        datos[9] = rs.getString(10);
        datos[10] = rs.getString(11);
        datos[11] = rs.getString(12);
        datos[12] = rs.getString(13);
        datos[13] = rs.getString(14);
        datos[14] = rs.getString(15);
        datos[15] = rs.getString(16);
        datos[16] = rs.getString(17);
        datos[17] = rs.getString(18);
        datos[18] = rs.getString(19);
        tconsulta.addRow(datos);
        }
        T_alumnos.setModel(tconsulta);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Error en la consulta");
        }
    }//GEN-LAST:event_A_consultarActionPerformed

    private void PL_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PL_consultarActionPerformed
        Connection con = null;
        con=getConnection();
        DefaultTableModel tconsulta = new DefaultTableModel();
        tconsulta.addColumn("ID_Plantel");
        tconsulta.addColumn("Tipo_Plantel");
        T_plantel.setModel(tconsulta);

        String []datos = new String[2];
        try{
        Statement leer = con.createStatement();
         rs = leer.executeQuery("SELECT * FROM tbl_plantel");
        while(rs.next()){
        datos[0] = rs.getString(1);
        datos[1] = rs.getString(2);
        
        tconsulta.addRow(datos);
        }
        T_plantel.setModel(tconsulta);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Error en la consulta");
        }
    }//GEN-LAST:event_PL_consultarActionPerformed

    private void T_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_consultarActionPerformed
        Connection con = null;
        con=getConnection();
        DefaultTableModel tconsulta = new DefaultTableModel();        
        tconsulta.addColumn("Nombre_T");
        tconsulta.addColumn("AP_T");
        tconsulta.addColumn("AM_T");
        tconsulta.addColumn("Sexo_T");
        tconsulta.addColumn("Edad_T");
        tconsulta.addColumn("Whatsapp_T");
        tconsulta.addColumn("Email_T");
        tconsulta.addColumn("NSS_T");
        tconsulta.addColumn("RFC_T");
        tconsulta.addColumn("Matricula");
        T_tutores.setModel(tconsulta);

        String []datos = new String[10];
        try{
            Statement leer = con.createStatement();
            rs = leer.executeQuery("SELECT * FROM tbl_tutor");
            while(rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);
                datos[7] = rs.getString(8);
                datos[8] = rs.getString(9);
                datos[9] = rs.getString(10);

                tconsulta.addRow(datos);
            }
            T_tutores.setModel(tconsulta);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error en la consulta");
        }
    }//GEN-LAST:event_T_consultarActionPerformed

    private void P_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_consultarActionPerformed
        Connection con = null;
        con=getConnection();
        DefaultTableModel tconsulta = new DefaultTableModel();
        tconsulta.addColumn("ID_Pago");
        tconsulta.addColumn("Cantidad_pago");
        tconsulta.addColumn("Metodo_Pago");
        tconsulta.addColumn("Fecha_Pago");
        tconsulta.addColumn("Mes");
        tconsulta.addColumn("Matricula");
        tconsulta.addColumn("Grado");
        tconsulta.addColumn("Grupo");
        tconsulta.addColumn("Tipo_Plantel");
        T_pago.setModel(tconsulta);

        String []datos = new String[8];
        try{
        Statement leer = con.createStatement();
            rs = leer.executeQuery("SELECT tbl_pago.ID_Pago, TBL_PAGO.Cantidad_pago, tbl_pago.Metodo_Pago, TBL_PAGO.Fecha_Pago, tbl_pago.Mes, TBL_Alumno.Matricula, tbl_pago.Grado, tbl_pago.Grupo, TBL_Plantel.Tipo_Plantel FROM tbl_pago  INNER JOIN tbl_alumno ON tbl_pago.matricula = tbl_alumno.matricula  INNER JOIN tbl_plantel ON tbl_plantel.id_plantel = tbl_alumno.id_plantel ORDER BY ID_Pago;");
            while(rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);
                datos[7] = rs.getString(8);
                datos[8] = rs.getString(9);
                tconsulta.addRow(datos);
        }
        T_pago.setModel(tconsulta);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Error en la consulta");
        }
    }//GEN-LAST:event_P_consultarActionPerformed

    private void C_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_consultarActionPerformed
        Connection con = null;
        con=getConnection();
        DefaultTableModel tconsulta = new DefaultTableModel();
        tconsulta.addColumn("ID_Colegiatura");
        tconsulta.addColumn("Cantidad_Co");
        tconsulta.addColumn("Fecha_Co");
        tconsulta.addColumn("Matricula");
        tconsulta.addColumn("ID_Corte");
        tconsulta.addColumn("ID_Pago");
        T_colegiatura.setModel(tconsulta);

        String []datos = new String[6];
        try{
        Statement leer = con.createStatement();
         rs = leer.executeQuery("SELECT * FROM tbl_colegiatura");
        while(rs.next()){
        datos[0] = rs.getString(1);
        datos[1] = rs.getString(2);
        datos[2] = rs.getString(3);
        datos[3] = rs.getString(4);
        datos[4] = rs.getString(5);
        datos[5] = rs.getString(6);
        tconsulta.addRow(datos);
        }
        T_colegiatura.setModel(tconsulta);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Error en la consulta");
        }
    }//GEN-LAST:event_C_consultarActionPerformed

    private void CR_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CR_consultarActionPerformed
        Connection con = null;
        con=getConnection();
        DefaultTableModel tconsulta = new DefaultTableModel();
        tconsulta.addColumn("ID_Corte");
        tconsulta.addColumn("Fecha_Inicio");
        tconsulta.addColumn("Fecha_Fin");
        T_corte.setModel(tconsulta);

        String []datos = new String[3];
        try{
        Statement leer = con.createStatement();
         rs = leer.executeQuery("SELECT * FROM tbl_corte");
        while(rs.next()){
            datos[0] = rs.getString(1);
            datos[1] = rs.getString(2);
            datos[2] = rs.getString(3);
            tconsulta.addRow(datos);
        }
        T_corte.setModel(tconsulta);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Error en la consulta");
        }
    }//GEN-LAST:event_CR_consultarActionPerformed

    private void label2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label2MouseClicked
        // TODO add your handling code here:
        DTabbed.setSelectedIndex(0);
    }//GEN-LAST:event_label2MouseClicked

    private void label3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label3MouseClicked
        // TODO add your handling code here:
        DTabbed.setSelectedIndex(1);
    }//GEN-LAST:event_label3MouseClicked

    private void label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label1MouseClicked
        // TODO add your handling code here:
        DTabbed.setSelectedIndex(2);
    }//GEN-LAST:event_label1MouseClicked

    private void label4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label4MouseClicked
        // TODO add your handling code here:
        DTabbed.setSelectedIndex(3);
    }//GEN-LAST:event_label4MouseClicked

    private void label5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label5MouseClicked
        // TODO add your handling code here:
        DTabbed.setSelectedIndex(6);
    }//GEN-LAST:event_label5MouseClicked

    private void label6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label6MouseClicked
        // TODO add your handling code here:
        DTabbed.setSelectedIndex(7);
    }//GEN-LAST:event_label6MouseClicked

    private void ConGIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConGIMouseClicked
        // TODO add your handling code here:
        Connection con = null;
        con=getConnection();
        DefaultTableModel tconsulta = new DefaultTableModel();
        tconsulta.addColumn("SUM(CANTIDAD_PAGO)");
        String matricula = MatriculaRI.getText();

        TablaRI.setModel(tconsulta);

        String []datos = new String[1];
        try{
            Statement leer = con.createStatement();
            rs = leer.executeQuery("SELECT SUM(CANTIDAD_PAGO) FROM tbl_pago WHERE MATRICULA= '"+matricula+"' ");
            while(rs.next()){
                datos[0] = rs.getString(1);

                tconsulta.addRow(datos);
            }
            TablaRI.setModel(tconsulta);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error en la consulta");
        }
    }//GEN-LAST:event_ConGIMouseClicked

    private void ConDIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConDIMouseClicked
        // TODO add your handling code here:
        Connection con = null;
        con=getConnection();
        DefaultTableModel tconsulta = new DefaultTableModel();
        tconsulta.addColumn("ID_Pago");
        tconsulta.addColumn("Cantidad_pago");
        tconsulta.addColumn("Metodo_Pago");
        tconsulta.addColumn("Fecha_Pago");
        tconsulta.addColumn("Mes");
        tconsulta.addColumn("Matricula");
        tconsulta.addColumn("Grado");
        tconsulta.addColumn("Grupo");
        tconsulta.addColumn("Tipo_Plantel");
        String matricula = MatriculaRI.getText();

        TablaRI.setModel(tconsulta);

        String []datos = new String[9];
        try{
            Statement leer = con.createStatement();
            rs = leer.executeQuery("SELECT tbl_pago.ID_Pago, TBL_PAGO.Cantidad_pago, tbl_pago.Metodo_Pago, TBL_PAGO.Fecha_Pago, tbl_pago.Mes, TBL_Alumno.Matricula, tbl_pago.Grado, tbl_pago.Grupo, TBL_Plantel.Tipo_Plantel FROM tbl_pago  INNER JOIN tbl_alumno ON tbl_pago.matricula = tbl_alumno.matricula  INNER JOIN tbl_plantel ON tbl_plantel.id_plantel = tbl_alumno.id_plantel WHERE tbl_pago.matricula= '"+matricula+"';");
            while(rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);
                datos[7] = rs.getString(8);
                datos[8] = rs.getString(9);

                tconsulta.addRow(datos);
            }
            TablaRI.setModel(tconsulta);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error en la consulta");
        }
    }//GEN-LAST:event_ConDIMouseClicked

    private void ConsultaDetalladaTodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultaDetalladaTodoMouseClicked
        // TODO add your handling code here:
        Connection con = null;
        con=getConnection();
        DefaultTableModel tconsulta = new DefaultTableModel();
        tconsulta.addColumn("ID_Pago");
        tconsulta.addColumn("Cantidad_pago");
        tconsulta.addColumn("Metodo_Pago");
        tconsulta.addColumn("Fecha_Pago");
        tconsulta.addColumn("Mes");
        tconsulta.addColumn("Matricula");
        tconsulta.addColumn("Grado");
        tconsulta.addColumn("Grupo");
        tconsulta.addColumn("Tipo_Plantel");
        String plantel = PlantelReporteGral.getSelectedItem().toString();
        int grado = Integer.parseInt(GradoRGGG.getSelectedItem().toString());
        String grupo = GrupoReporteGral.getSelectedItem().toString();

        ReporteGralTabla.setModel(tconsulta);

        String []datos = new String[9];
        try{
            Statement leer = con.createStatement();
            rs = leer.executeQuery("SELECT tbl_pago.ID_Pago, TBL_PAGO.Cantidad_pago, tbl_pago.Metodo_Pago, TBL_PAGO.Fecha_Pago, tbl_pago.Mes, TBL_Alumno.Matricula, tbl_pago.Grado, tbl_pago.Grupo, TBL_Plantel.Tipo_Plantel FROM tbl_pago  INNER JOIN tbl_alumno ON tbl_pago.matricula = tbl_alumno.matricula  INNER JOIN tbl_plantel ON tbl_plantel.id_plantel = tbl_alumno.id_plantel WHERE tbl_plantel.tipo_plantel= '"+plantel+"' AND tbl_pago.grado='"+grado+"' AND tbl_pago.grupo='"+grupo+"' ;");
            while(rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);
                datos[7] = rs.getString(8);
                datos[8] = rs.getString(9);

                tconsulta.addRow(datos);
            }
            ReporteGralTabla.setModel(tconsulta);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error en la consulta");
        }
    }//GEN-LAST:event_ConsultaDetalladaTodoMouseClicked

    private void ConsultaGralGradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultaGralGradoMouseClicked
        // TODO add your handling code here:
        Connection con = null;
        con=getConnection();
        DefaultTableModel tconsulta = new DefaultTableModel();
        tconsulta.addColumn("ID_Pago");
        tconsulta.addColumn("Cantidad_pago");
        tconsulta.addColumn("Metodo_Pago");
        tconsulta.addColumn("Fecha_Pago");
        tconsulta.addColumn("Mes");
        tconsulta.addColumn("Matricula");
        tconsulta.addColumn("Grado");
        tconsulta.addColumn("Grupo");
        tconsulta.addColumn("Tipo_Plantel");
        int grado = Integer.parseInt(GradoRGGG.getSelectedItem().toString());

        ReporteGralTabla.setModel(tconsulta);

        String []datos = new String[9];
        try{
            Statement leer = con.createStatement();
            rs = leer.executeQuery("SELECT tbl_pago.ID_Pago, TBL_PAGO.Cantidad_pago, tbl_pago.Metodo_Pago, TBL_PAGO.Fecha_Pago, tbl_pago.Mes, TBL_Alumno.Matricula, tbl_pago.Grado, tbl_pago.Grupo, TBL_Plantel.Tipo_Plantel FROM tbl_pago  INNER JOIN tbl_alumno ON tbl_pago.matricula = tbl_alumno.matricula  INNER JOIN tbl_plantel ON tbl_plantel.id_plantel = tbl_alumno.id_plantel WHERE tbl_pago.grado= '"+grado+"';");
            while(rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);
                datos[7] = rs.getString(8);
                datos[8] = rs.getString(9);

                tconsulta.addRow(datos);
            }
            ReporteGralTabla.setModel(tconsulta);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error en la consulta");
        }
    }//GEN-LAST:event_ConsultaGralGradoMouseClicked

    private void ConsultaGralGrupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultaGralGrupoMouseClicked
        // TODO add your handling code here:
        Connection con = null;
        con=getConnection();
        DefaultTableModel tconsulta = new DefaultTableModel();
        tconsulta.addColumn("SUM(CANTIDAD_PAGO)");
        String grupo = GrupoReporteGral.getSelectedItem().toString();

        TablaRI.setModel(tconsulta);

        String []datos = new String[1];
        try{
            Statement leer = con.createStatement();
            rs = leer.executeQuery("SELECT SUM(CANTIDAD_PAGO) FROM tbl_pago WHERE GRUPO= '"+grupo+"';");
            while(rs.next()){
                datos[0] = rs.getString(1);

                tconsulta.addRow(datos);
            }
            ReporteGralTabla.setModel(tconsulta);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error en la consulta");
        }
    }//GEN-LAST:event_ConsultaGralGrupoMouseClicked

    private void ConsultaDetalladaPlantelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultaDetalladaPlantelMouseClicked
        // TODO add your handling code here:
        Connection con = null;
        con=getConnection();
        DefaultTableModel tconsulta = new DefaultTableModel();
        tconsulta.addColumn("SUM(CANTIDAD_PAGO)");
        String plantel = PlantelReporteGral.getSelectedItem().toString();

        TablaRI.setModel(tconsulta);

        String []datos = new String[1];
        try{
            Statement leer = con.createStatement();
            rs = leer.executeQuery("SELECT SUM(CANTIDAD_PAGO) FROM tbl_pago INNER JOIN tbl_alumno ON tbl_pago.matricula = tbl_alumno.matricula  INNER JOIN tbl_plantel ON tbl_plantel.id_plantel = tbl_alumno.id_plantel WHERE tbl_plantel.tipo_plantel= '"+plantel+"';");
            while(rs.next()){
                datos[0] = rs.getString(1);

                tconsulta.addRow(datos);
            }
            ReporteGralTabla.setModel(tconsulta);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error en la consulta");
        }
    }//GEN-LAST:event_ConsultaDetalladaPlantelMouseClicked

    private void ConsultaDetalladaGrado1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultaDetalladaGrado1MouseClicked
        // TODO add your handling code here:

        Connection con = null;
        con=getConnection();
        DefaultTableModel tconsulta = new DefaultTableModel();
        tconsulta.addColumn("SUM(CANTIDAD_PAGO)");
        int grado = Integer.parseInt(GradoRGGG.getSelectedItem().toString());

        TablaRI.setModel(tconsulta);

        String []datos = new String[1];
        try{
            Statement leer = con.createStatement();
            rs = leer.executeQuery("SELECT SUM(CANTIDAD_PAGO) FROM tbl_pago WHERE GRADO= '"+grado+"';");
            while(rs.next()){
                datos[0] = rs.getString(1);

                tconsulta.addRow(datos);
            }
            ReporteGralTabla.setModel(tconsulta);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error en la consulta");
        }
    }//GEN-LAST:event_ConsultaDetalladaGrado1MouseClicked

    private void ConsultaGralPlantelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultaGralPlantelMouseClicked
        // TODO add your handling code here:
        Connection con = null;
        con=getConnection();
        DefaultTableModel tconsulta = new DefaultTableModel();
        tconsulta.addColumn("ID_Pago");
        tconsulta.addColumn("Cantidad_pago");
        tconsulta.addColumn("Metodo_Pago");
        tconsulta.addColumn("Fecha_Pago");
        tconsulta.addColumn("Mes");
        tconsulta.addColumn("Matricula");
        tconsulta.addColumn("Grado");
        tconsulta.addColumn("Grupo");
        tconsulta.addColumn("Tipo_Plantel");
        String plantel = PlantelReporteGral.getSelectedItem().toString();

        ReporteGralTabla.setModel(tconsulta);

        String []datos = new String[9];
        try{
            Statement leer = con.createStatement();
            rs = leer.executeQuery("SELECT tbl_pago.ID_Pago, TBL_PAGO.Cantidad_pago, tbl_pago.Metodo_Pago, TBL_PAGO.Fecha_Pago, tbl_pago.Mes, TBL_Alumno.Matricula, tbl_pago.Grado, tbl_pago.Grupo, TBL_Plantel.Tipo_Plantel FROM tbl_pago  INNER JOIN tbl_alumno ON tbl_pago.matricula = tbl_alumno.matricula  INNER JOIN tbl_plantel ON tbl_plantel.id_plantel = tbl_alumno.id_plantel WHERE tbl_plantel.tipo_plantel= '"+plantel+"';");
            while(rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);
                datos[7] = rs.getString(8);
                datos[8] = rs.getString(9);

                tconsulta.addRow(datos);
            }
            ReporteGralTabla.setModel(tconsulta);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error en la consulta");
        }
    }//GEN-LAST:event_ConsultaGralPlantelMouseClicked

    private void ConsultaDetalladaGrupo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultaDetalladaGrupo1MouseClicked
        // TODO add your handling code here:
        Connection con = null;
        con=getConnection();
        DefaultTableModel tconsulta = new DefaultTableModel();
        tconsulta.addColumn("ID_Pago");
        tconsulta.addColumn("Cantidad_pago");
        tconsulta.addColumn("Metodo_Pago");
        tconsulta.addColumn("Fecha_Pago");
        tconsulta.addColumn("Mes");
        tconsulta.addColumn("Matricula");
        tconsulta.addColumn("Grado");
        tconsulta.addColumn("Grupo");
        tconsulta.addColumn("Tipo_Plantel");
        String grupo = GrupoReporteGral.getSelectedItem().toString();

        ReporteGralTabla.setModel(tconsulta);

        String []datos = new String[9];
        try{
            Statement leer = con.createStatement();
            rs = leer.executeQuery("SELECT tbl_pago.ID_Pago, TBL_PAGO.Cantidad_pago, tbl_pago.Metodo_Pago, TBL_PAGO.Fecha_Pago, tbl_pago.Mes, TBL_Alumno.Matricula, tbl_pago.Grado, tbl_pago.Grupo, TBL_Plantel.Tipo_Plantel FROM tbl_pago  INNER JOIN tbl_alumno ON tbl_pago.matricula = tbl_alumno.matricula  INNER JOIN tbl_plantel ON tbl_plantel.id_plantel = tbl_alumno.id_plantel WHERE tbl_pago.grupo= '"+grupo+"';");
            while(rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);
                datos[7] = rs.getString(8);
                datos[8] = rs.getString(9);

                tconsulta.addRow(datos);
            }
            ReporteGralTabla.setModel(tconsulta);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error en la consulta");
        }

    }//GEN-LAST:event_ConsultaDetalladaGrupo1MouseClicked

    private void ConsultaGralTodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultaGralTodoMouseClicked
        // TODO add your handling code here:

        Connection con = null;
        con=getConnection();
        DefaultTableModel tconsulta = new DefaultTableModel();
        tconsulta.addColumn("SUM(CANTIDAD_PAGO)");
        String plantel = PlantelReporteGral.getSelectedItem().toString();
        int grado = Integer.parseInt(GradoRGGG.getSelectedItem().toString());
        String grupo = GrupoReporteGral.getSelectedItem().toString();

        TablaRI.setModel(tconsulta);

        String []datos = new String[1];
        try{
            Statement leer = con.createStatement();
            rs = leer.executeQuery("SELECT SUM(CANTIDAD_PAGO) FROM tbl_pago INNER JOIN tbl_alumno ON tbl_pago.matricula = tbl_alumno.matricula  INNER JOIN tbl_plantel ON tbl_plantel.id_plantel = tbl_alumno.id_plantel WHERE tbl_plantel.tipo_plantel= '"+plantel+"' AND tbl_pago.grado='"+grado+"' AND tbl_pago.grupo='"+grupo+"' ;");
            while(rs.next()){
                datos[0] = rs.getString(1);

                tconsulta.addRow(datos);
            }
            ReporteGralTabla.setModel(tconsulta);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error en la consulta");
        }
    }//GEN-LAST:event_ConsultaGralTodoMouseClicked

    private void label7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label7MouseClicked
        // TODO add your handling code here:
        DTabbed.setSelectedIndex(4);
    }//GEN-LAST:event_label7MouseClicked

    private void label8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label8MouseClicked
        // TODO add your handling code here:
        DTabbed.setSelectedIndex(5);
    }//GEN-LAST:event_label8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oDTabbedvase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Direc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Direc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Direc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Direc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Direc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A_consultar;
    private javax.swing.JButton CR_consultar;
    private javax.swing.JButton C_consultar;
    private java.awt.Label ConDI;
    private java.awt.Label ConGI;
    private java.awt.Label ConsultaDetalladaGrado1;
    private java.awt.Label ConsultaDetalladaGrupo1;
    private java.awt.Label ConsultaDetalladaPlantel;
    private java.awt.Label ConsultaDetalladaTodo;
    private java.awt.Label ConsultaGralGrado;
    private java.awt.Label ConsultaGralGrupo;
    private java.awt.Label ConsultaGralPlantel;
    private java.awt.Label ConsultaGralTodo;
    private javax.swing.JTabbedPane DTabbed;
    private javax.swing.JComboBox<String> GradoRGGG;
    private javax.swing.JComboBox<String> GrupoReporteGral;
    private javax.swing.JTextField MatriculaRI;
    private javax.swing.JButton PL_consultar;
    private javax.swing.JButton P_consultar;
    private javax.swing.JComboBox<String> PlantelReporteGral;
    private javax.swing.JTable ReporteGralTabla;
    private javax.swing.JTable T_alumnos;
    private javax.swing.JTable T_colegiatura;
    private javax.swing.JButton T_consultar;
    private javax.swing.JTable T_corte;
    private javax.swing.JTable T_pago;
    private javax.swing.JTable T_plantel;
    private javax.swing.JTable T_tutores;
    private javax.swing.JTable TablaRI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    // End of variables declaration//GEN-END:variables
}
