/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import controlescolar.Conexion;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.awt.print.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author USER
 */
public class Recibo extends javax.swing.JFrame implements Printable {

    /**
     * Creates new form Recibo
     */
    Conexion conexion = new Conexion();
    PreparedStatement ps;
    ResultSet rs;
    DefaultTableModel modelo;
    public static final String URL ="jdbc:mysql://localhost:3306/controlescolar";
    public static final String usuario="root";
    public static final String contraseña="l0v3s70r717309";
    
    public Connection getConnection(){
        Connection con=null;
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
             con=(Connection) DriverManager.getConnection(URL,usuario,contraseña); 
        }catch(Exception ex){
            System.err.println("Error"+ex);
        }
        return con;
    }
    public Recibo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Recibo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Matricula = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Fecha = new javax.swing.JTextField();
        Mes = new javax.swing.JTextField();
        Colegiatura = new javax.swing.JTextField();
        Cantidad = new javax.swing.JTextField();
        Metodo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Factura = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Plantel = new javax.swing.JTextField();
        Imprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Recibo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel1.setText("FACTURA:");

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel2.setText("LOS ANGELITOS GUERRERENSES");

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel3.setText("MATRÍCULA:");

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel4.setText("NOMBRE:");

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel5.setText("FECHA:");

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel6.setText("COLEGIATURA:");

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel7.setText("CANTIDAD:");

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel8.setText("MÉTODO:");

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel9.setText("MES:");

        Matricula.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Matricula.setBorder(null);
        Matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatriculaActionPerformed(evt);
            }
        });

        Nombre.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Nombre.setBorder(null);

        Fecha.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Fecha.setBorder(null);

        Mes.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Mes.setBorder(null);

        Colegiatura.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Colegiatura.setBorder(null);

        Cantidad.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Cantidad.setBorder(null);

        Metodo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Metodo.setBorder(null);

        jLabel10.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel10.setText("-----------------------------------------------------");

        jLabel11.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel11.setText("-----------------------------------------------------");

        jLabel12.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel12.setText("ACAPULCO, GUERRERO.");

        jLabel13.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel13.setText("-----------------------------------------------------");

        jLabel14.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("SOFTMAXCI S.A DE C.V");

        jLabel16.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("EL SOFTWARE DE TUS PENSAMIENTO");

        Factura.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Factura.setBorder(null);
        Factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacturaActionPerformed(evt);
            }
        });
        Factura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FacturaKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel15.setText("PLANTEL:");

        Plantel.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Plantel.setBorder(null);

        javax.swing.GroupLayout ReciboLayout = new javax.swing.GroupLayout(Recibo);
        Recibo.setLayout(ReciboLayout);
        ReciboLayout.setHorizontalGroup(
            ReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReciboLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(ReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(ReciboLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel12))
                    .addGroup(ReciboLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Factura, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(121, 121, 121))
            .addGroup(ReciboLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(ReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReciboLayout.createSequentialGroup()
                        .addGroup(ReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Colegiatura, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Metodo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ReciboLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel10))
                    .addGroup(ReciboLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Plantel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ReciboLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel13))
                    .addComponent(jLabel11))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReciboLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReciboLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReciboLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(150, 150, 150))))
        );
        ReciboLayout.setVerticalGroup(
            ReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReciboLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(27, 27, 27)
                .addGroup(ReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(4, 4, 4)
                .addGroup(ReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Plantel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(27, 27, 27)
                .addGroup(ReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReciboLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addGap(22, 22, 22))
                    .addGroup(ReciboLayout.createSequentialGroup()
                        .addGroup(ReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Colegiatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Metodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(101, Short.MAX_VALUE))))
        );

        Imprimir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Imprimir.setText("Imprimir");
        Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Recibo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(Imprimir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Recibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Imprimir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatriculaActionPerformed
        // TODO add your handling code here:Connection con = null;
     /*   Connection con = null;
        try{
            con=getConnection();
            String matricula = Matricula.getText();
            PreparedStatement ps = con.prepareStatement("SELECT tbl_pago.ID_Pago, TBL_PAGO.Cantidad_pago, tbl_pago.Metodo_Pago, TBL_PAGO.Fecha_Pago, tbl_pago.Mes, TBL_Alumno.Matricula, TBL_Alumno.Nombre_A, TBL_Alumno.AP_A, TBL_Alumno.AM_A, TBL_COLEGIATURA.Cantidad_Co, TBL_COLEGIATURA.ID_Colegiatura FROM tbl_pago  INNER JOIN tbl_alumno ON tbl_pago.matricula = tbl_alumno.matricula  INNER JOIN tbl_colegiatura ON tbl_pago.id_colegiatura = tbl_colegiatura.id_colegiatura WHERE tbl_pago.matricula= '"+matricula+"'");
            rs = ps.executeQuery();
            if(rs.next()){
                
            String nmbr = rs.getString("Nombre_A");
            String ap = rs.getString("AP_A");
            String am = rs.getString("AM_A");
            String nc = nmbr + " " + ap + " " + am;
            
                Factura.setText(rs.getString("ID_Pago"));
                 
                Nombre.setText(nc);
                Plantel.setText(rs.getString("ID_Colegiatura"));
                
                Fecha.setText(rs.getString("Fecha_Pago"));
                Mes.setText(rs.getString("Mes"));
                Colegiatura.setText(rs.getString("Cantidad_Co"));
                Cantidad.setText(rs.getString("Cantidad_Pago"));
                Metodo.setText(rs.getString("Metodo_Pago"));

            }
            else{
                JOptionPane.showMessageDialog(null, "No existe un pago con esa ID");
            }
        }
        catch(Exception e){
            System.out.print(e);
        }*/
    }//GEN-LAST:event_MatriculaActionPerformed

    private void FacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FacturaActionPerformed

    private void ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirActionPerformed
        // TODO add your handling code here:
        try{
	PrinterJob gap = PrinterJob.getPrinterJob();
	gap.setPrintable(this);
	boolean top = gap.printDialog();
	if(top){
		gap.print();
		
	}	
    }
    catch(PrinterException ex){
	JOptionPane.showMessageDialog(null, "ERROR DE PROGRAMA", "ERROR\n" + ex, JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_ImprimirActionPerformed

    private void FacturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FacturaKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                Connection con = null;
        try{
            con=getConnection();
            String fact = Factura.getText();
            PreparedStatement ps = con.prepareStatement("SELECT tbl_pago.ID_Pago, TBL_PAGO.Cantidad_pago, tbl_pago.Metodo_Pago, TBL_PAGO.Fecha_Pago, tbl_pago.Mes, TBL_Alumno.Matricula, TBL_Alumno.Nombre_A, TBL_Alumno.AP_A, TBL_Alumno.AM_A, TBL_COLEGIATURA.Cantidad_Co, TBL_COLEGIATURA.ID_Colegiatura FROM tbl_pago  INNER JOIN tbl_alumno ON tbl_pago.matricula = tbl_alumno.matricula  INNER JOIN tbl_colegiatura ON tbl_pago.id_pago = tbl_colegiatura.id_pago WHERE tbl_pago.id_Pago= '"+fact+"' ");
            rs = ps.executeQuery();
            if(rs.next()){
                
            String nmbr = rs.getString("Nombre_A");
            String ap = rs.getString("AP_A");
            String am = rs.getString("AM_A");
            String nc = nmbr + " " + ap + " " + am;
            
                Matricula.setText(rs.getString("MAtricula"));
                 
                Nombre.setText(nc);
                Plantel.setText(rs.getString("ID_Colegiatura"));
                
                Fecha.setText(rs.getString("Fecha_Pago"));
                Mes.setText(rs.getString("Mes"));
                Colegiatura.setText(rs.getString("Cantidad_Co"));
                Cantidad.setText(rs.getString("Cantidad_Pago"));
                Metodo.setText(rs.getString("Metodo_Pago"));

            }
            else{
                JOptionPane.showMessageDialog(null, "No existe un pago con esa ID");
            }
        }
        catch(Exception e){
            System.out.print(e);
        }
       }
    }//GEN-LAST:event_FacturaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Recibo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cantidad;
    private javax.swing.JTextField Colegiatura;
    private javax.swing.JTextField Factura;
    private javax.swing.JTextField Fecha;
    private javax.swing.JButton Imprimir;
    private javax.swing.JTextField Matricula;
    private javax.swing.JTextField Mes;
    private javax.swing.JTextField Metodo;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Plantel;
    private javax.swing.JPanel Recibo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graf, PageFormat pagefor, int index) throws PrinterException {
        if(index>0){
                return NO_SUCH_PAGE;
        }

        Graphics2D hub = (Graphics2D) graf;
        hub.translate(pagefor.getImageableX() + 30,pagefor.getImageableY() + 30);
        hub.scale(1.0, 1.0);

        Recibo.printAll(graf);
        return PAGE_EXISTS;
    }
}
