/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import controlescolar.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Seg extends javax.swing.JFrame {
    
    Conexion conexion = new Conexion();
    PreparedStatement ps;
    ResultSet rs;
    DefaultTableModel modelo;
    public static final String URL ="jdbc:mysql://localhost:3306/controlescolar";
    public static final String usuario="root";
    public static final String contraseña="l0v3s70r717309";
    
    public Connection getConnection(){
        Connection con=null;
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
             con=(Connection) DriverManager.getConnection(URL,usuario,contraseña);
     
        }catch(Exception ex){
            System.err.println("Error"+ex);
        }
        return con;
    }
    
    public Seg() {
        initComponents();
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        MatriculaSeg = new javax.swing.JTextField();
        ConsultarSeg = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Verde = new javax.swing.JPanel();
        Amarillo = new javax.swing.JPanel();
        Rojo = new javax.swing.JPanel();
        fotolabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        alumno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 194));

        jPanel3.setBackground(new java.awt.Color(255, 255, 194));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Matricula: ");

        MatriculaSeg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        ConsultarSeg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ConsultarSeg.setText("Consultar");
        ConsultarSeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarSegActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        Verde.setBackground(java.awt.Color.lightGray);
        Verde.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout VerdeLayout = new javax.swing.GroupLayout(Verde);
        Verde.setLayout(VerdeLayout);
        VerdeLayout.setHorizontalGroup(
            VerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );
        VerdeLayout.setVerticalGroup(
            VerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );

        Amarillo.setBackground(java.awt.Color.lightGray);

        javax.swing.GroupLayout AmarilloLayout = new javax.swing.GroupLayout(Amarillo);
        Amarillo.setLayout(AmarilloLayout);
        AmarilloLayout.setHorizontalGroup(
            AmarilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );
        AmarilloLayout.setVerticalGroup(
            AmarilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        Rojo.setBackground(java.awt.Color.lightGray);

        javax.swing.GroupLayout RojoLayout = new javax.swing.GroupLayout(Rojo);
        Rojo.setLayout(RojoLayout);
        RojoLayout.setHorizontalGroup(
            RojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );
        RojoLayout.setVerticalGroup(
            RojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Amarillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Verde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(Verde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Amarillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Rojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Alumno/a:");

        alumno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        alumno.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fotolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MatriculaSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alumno)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(ConsultarSeg)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(MatriculaSeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(alumno))
                .addGap(4, 4, 4)
                .addComponent(fotolabel, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(ConsultarSeg)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultarSegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarSegActionPerformed
        // TODO add your handling code here:
        
        //ArrayList<String> estatus = getEstatus();
        Connection con = null;
        
        //ArrayList<String> array = new ArrayList<String>();
       try{
            con = getConnection();
           String matricula = MatriculaSeg.getText(); 
           ps =  con.prepareStatement("SELECT SUM(CANTIDAD_PAGO) FROM tbl_pago WHERE MATRICULA= '"+matricula+"'");
           rs = ps.executeQuery();
           rs.next();
           double cant = Double.parseDouble(rs.getString(1));
           
           double verdeK = 13232;
           double amarilloK = 6616;
           double rojoK = 0;
           
           double verdeP = 12828;
           double amarilloP = 6414;
           double rojoP = 0;
           
           double verdeS = 11312;
           double amarilloS = 5656;
           double rojoS = 0;
           
           if(cant >= verdeK || cant >= verdeP || cant >= verdeS){
               Verde.setBackground(Color.GREEN);
               Amarillo.setBackground(Color.LIGHT_GRAY);
               Rojo.setBackground(Color.LIGHT_GRAY);
               
           }
           else{
               if(cant == amarilloK || cant == amarilloP || cant == amarilloS){
                   Amarillo.setBackground(Color.YELLOW);
                   Verde.setBackground(Color.LIGHT_GRAY);
                   Rojo.setBackground(Color.LIGHT_GRAY);
               }
               else{
                   if(cant == rojoK || cant == rojoP || cant == rojoS){
                       Rojo.setBackground(Color.RED);
                        Verde.setBackground(Color.LIGHT_GRAY);
                        Amarillo.setBackground(Color.LIGHT_GRAY);
                   }
               }
           }
        
          getFoto();
          getNombre();
           
           
           
         
        }
       catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex + "Error al consultar estatus. Matricula no valida");
        }
       

    }//GEN-LAST:event_ConsultarSegActionPerformed

    
    
    public void getFoto() throws SQLException{
        Connection con = null;

        try{
        con = getConnection();
        String matricula = MatriculaSeg.getText();
        ps = con.prepareStatement("SELECT Ruta_Foto from tbl_alumno WHERE MATRICULA= '"+matricula+"'");
        rs = ps.executeQuery();
        if(rs.next()){
           Image foto = getToolkit().getImage(rs.getString("Ruta_Foto"));
           foto = foto.getScaledInstance(110, 110, Image.SCALE_DEFAULT);
           fotolabel.setIcon(new ImageIcon(foto));
        }     
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex + "Error al encontrar foto");
        }
    }
        
        public void getNombre() throws SQLException{
        Connection con = null;
 
        try{
        String matricula = MatriculaSeg.getText();
        con = getConnection();
        ps = con.prepareStatement("SELECT Nombre_A, AP_A, AM_A FROM tbl_alumno WHERE MATRICULA= '"+matricula+"'");
        rs = ps.executeQuery();
        if(rs.next()){
        String nmbr = rs.getString("Nombre_A");
        String ap = rs.getString("AP_A");
        String am = rs.getString("AM_A");
        String nc = nmbr + " " + ap + " " + am;
        alumno.setText(nc);
        }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex + "Error al encontrar nombre");
        }
        }
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seg().setVisible(true);
            }
        });
    }
    
    
    
   /*    public String setEstatus(){
        Connection con = null;
        String matricula = MatriculaSeg.getText();
        //ArrayList<String> array = new ArrayList<String>();
       try{
            con = getConnection();
            
           String query = "SELECT SUM(CANTIDAD_PAGO) FROM tbl_pago WHERE MATRICULA= '"+matricula+"'";
            
            Statement stmt = con.createStatement();
            stmt.executeUpdate(query);   
            

             
        }
       catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex + "Error al consultar estatus");
        }

    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Amarillo;
    private javax.swing.JButton ConsultarSeg;
    private javax.swing.JTextField MatriculaSeg;
    private javax.swing.JPanel Rojo;
    private javax.swing.JPanel Verde;
    private javax.swing.JLabel alumno;
    private javax.swing.JLabel fotolabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
